/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.evtstore;

import org.evtstore.domain.ex.DomainExample;
import org.evtstore.domain.ex.ExampleAgg;

public class MemoryTest extends ProviderTester {
    public static DomainExample domain = new DomainExample("test1");

    @Override
    public Domain<ExampleAgg> getDomain() {
        return domain;
    }
}
