/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.evtstore;

import org.evtstore.domain.ex.DomainExample;
import org.evtstore.domain.ex.ExampleAgg;
import org.evtstore.provider.Neo4jProvider;
import org.junit.BeforeClass;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;

public class Neo4jTest extends ProviderTester {
  public static DomainExample domain;

  @BeforeClass
  public static void before() {
    var driver = GraphDatabase.driver("bolt://localhost:30010", AuthTokens.basic("neo4j", "admin"));
    var session = driver.session();
    session.run("MATCH (n: JEvents) DETACH DELETE n");
    session.run("MATCH (n: JBookmarks) DETACH DELETE n");
    var provider = new Neo4jProvider<ExampleAgg>(session, "JEvents", "JBookmarks");
    provider.migrate();
    Neo4jTest.domain = new DomainExample(provider, "test1");
  }

  @Override
  public Domain<ExampleAgg> getDomain() {
    return domain;
  }
}
